# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    context-path: /uapi
spring:
  profiles:
    active: dev
  application:
    name: U-Space-2.X
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
